apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-postgres-access
spec:
  podSelector:
    matchLabels:
      app: postgres
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: service2
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: restrict-service2-access
spec:
  podSelector:
    matchLabels:
      app: service2
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: service1